routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /offline/: offline

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
